name: gitartwork from a contribution graph
on: 
  push:
  schedule:
    - cron: '* */24 * * *'
workflow_dispatch:
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           # Use this username's contribution graph  
           user_name: TahirAAnny
           # Text on contribution graph 
           text: TAHIRA
